# Generated by Django 4.2.3 on 2023-07-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loproposal',
            name='endorsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loproposal',
            name='endorser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endorser', to='ops.user'),
        ),
        migrations.AddField(
            model_name='loproposal',
            name='h',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='loproposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposer', to='ops.user'),
        ),
        migrations.CreateModel(
            name='Lo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled', models.BooleanField(default=False)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ops.loproposal')),
            ],
        ),
    ]
