# Generated by Django 4.2.3 on 2023-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_loproposal_endorsed_loproposal_endorser_loproposal_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loproposal',
            name='h',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
