# Generated by Django 4.2.3 on 2023-07-23 14:08

from django.db import migrations, models
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_loproposal_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='loproposal',
            name='proposed_on',
            field=models.BigIntegerField(default=ops.models.current_time_millis),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_on',
            field=models.BigIntegerField(default=ops.models.current_time_millis),
        ),
    ]
