# Generated by Django 4.2.3 on 2023-07-25 12:11

from django.db import migrations, models
import django.db.models.deletion
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_loproposal_proposed_on_user_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loproposal',
            name='proposed_on',
            field=models.BigIntegerField(blank=True, default=ops.models.current_time_millis),
        ),
        migrations.CreateModel(
            name='UserInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_id', models.CharField(max_length=26)),
                ('address', models.TextField()),
                ('occupation', models.JSONField()),
                ('other_jobs', models.TextField()),
                ('income', models.JSONField()),
                ('last_saved', models.BigIntegerField(default=ops.models.current_time_millis)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ops.user')),
            ],
        ),
    ]
