# Generated by Django 4.2.3 on 2023-07-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_alter_loproposal_proposed_on_userinsights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loproposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(db_comment='Letter code of country', max_length=5),
        ),
    ]
