# Generated by Django 4.2.3 on 2023-07-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_alter_loproposal_user_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinsights',
            name='nat_id',
            field=models.CharField(editable=False, max_length=26, unique=True),
        ),
    ]
