# Generated by Django 4.2.3 on 2023-07-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_alter_userinsights_nat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_closed', models.BooleanField(default=False)),
                ('auctioneer', models.ForeignKey(db_comment='the borrower', on_delete=django.db.models.deletion.PROTECT, related_name='auctioneer', to='ops.user')),
                ('bid', models.ForeignKey(db_comment='the bid application', on_delete=django.db.models.deletion.PROTECT, to='ops.loproposal')),
                ('bidder', models.ForeignKey(db_comment='the lender bidding', on_delete=django.db.models.deletion.PROTECT, related_name='bidder', to='ops.user')),
            ],
        ),
    ]
