# Generated by Django 4.2.3 on 2023-07-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_closed',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_status',
            field=models.SmallIntegerField(choices=[(1, 'Accepted'), (0, 'Pending'), (-1, 'Cancelled')], default=0),
        ),
    ]
