# Generated by Django 4.2.3 on 2023-07-29 05:23

from django.db import migrations, models
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_remove_bid_bid_closed_bid_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.BigIntegerField(default=ops.models.current_time_millis),
        ),
        migrations.AlterField(
            model_name='loproposal',
            name='proposed_on',
            field=models.BigIntegerField(default=ops.models.current_time_millis),
        ),
    ]
