# Generated by Django 4.2.3 on 2023-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_bid_bid_time_alter_loproposal_proposed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='seal_time',
            field=models.BigIntegerField(db_comment='time when bid was closed', null=True),
        ),
    ]
