# Generated by Django 4.2.3 on 2023-08-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_bid_seal_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loproposal',
            old_name='endorsed',
            new_name='case_closed',
        ),
        migrations.RemoveField(
            model_name='loproposal',
            name='endorser',
        ),
        migrations.AddField(
            model_name='loproposal',
            name='closer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closer', to='ops.user'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_status',
            field=models.SmallIntegerField(choices=[(1, 'Confirmed'), (0, 'Pending'), (-1, 'Cancelled')], default=0),
        ),
    ]
