# Generated by Django 4.2.3 on 2023-08-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_rename_endorsed_loproposal_case_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='seal_time',
            new_name='close_time',
        ),
    ]
