# Generated by Django 4.2.3 on 2023-08-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_rename_seal_time_bid_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loproposal',
            name='destination',
            field=models.JSONField(default={'detail': '06596', 'method': 'mpesa'}),
        ),
        migrations.AlterField(
            model_name='loproposal',
            name='h',
            field=models.IntegerField(default=1000),
        ),
    ]
