# Generated by Django 4.2.3 on 2023-08-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_alter_loproposal_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loproposal',
            name='destination',
            field=models.JSONField(default={'detail': '06596', 'method': 'mpesa'}),
        ),
    ]
