# Generated by Django 4.2.3 on 2023-08-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_alter_loproposal_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='loproposal',
            name='close_time',
            field=models.BigIntegerField(db_comment='time when case was closed', null=True),
        ),
        migrations.AlterField(
            model_name='loproposal',
            name='destination',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctioneer_conf', models.BooleanField(default=False)),
                ('auctioneer_conf_time', models.BigIntegerField(null=True)),
                ('bidder_conf', models.BooleanField(default=False)),
                ('bidder_conf_time', models.BigIntegerField(null=True)),
                ('close_time', models.BigIntegerField(null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.bid')),
            ],
        ),
    ]
