# Generated by Django 4.2.3 on 2023-08-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_loproposal_close_time_alter_loproposal_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='proposal',
        ),
    ]
