# Generated by Django 4.2.3 on 2023-08-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_rename_bid_bid_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.bid', unique=True),
        ),
    ]
