# Generated by Django 4.2.3 on 2023-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_alter_pendingtransaction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='source',
            field=models.JSONField(null=True),
        ),
    ]
