# Generated by Django 4.2.3 on 2023-08-14 15:29

from django.db import migrations, models
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_bid_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='initiation_time',
            field=models.BigIntegerField(default=ops.models.current_time_millis),
        ),
    ]
