# Generated by Django 4.2.3 on 2023-08-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_pendingtransaction_initiation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lo',
            name='bid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='ops.bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ops.bid'),
        ),
    ]
