# Generated by Django 4.2.3 on 2023-08-17 14:24

from django.db import migrations, models
import django.db.models.deletion
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_lo_bid_alter_pendingtransaction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lo',
            name='payback',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lo',
            name='wk_instalment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lo',
            name='wk_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('instalment_time', models.BigIntegerField(default=ops.models.current_time_millis)),
                ('percent_complete', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.lo')),
            ],
        ),
    ]
