# Generated by Django 4.2.3 on 2023-08-19 06:56

from django.db import migrations, models
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_lo_payback_lo_wk_instalment_lo_wk_rate_instalment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lo',
            name='finished_on',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lo',
            name='initiated_on',
            field=models.BigIntegerField(default=ops.models.current_time_millis),
        ),
    ]
