# Generated by Django 4.2.3 on 2023-08-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_lo_finished_on_lo_initiated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalment',
            name='percent_complete',
        ),
    ]
