# Generated by Django 4.2.3 on 2023-08-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_remove_instalment_percent_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
