# Generated by Django 4.2.3 on 2023-08-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_instalment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalment',
            name='source',
            field=models.JSONField(null=True),
        ),
    ]
