# Generated by Django 4.2.3 on 2023-08-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_instalment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalment',
            name='source',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
